package models.enums;

public enum Criteria {
    SIZE_IN_ASCENDING,
        SIZE_IN_DESCENDING,
    COLOR_IN_ASCENDING,
        COLOR_IN_DESCENDING,
    FABRIC_IN_ASCENDING,
        FABRIC_IN_DESCENDING,
    SIZE_AND_COLOR_AND_FABRIC_IN_ASCENDING,
        SIZE_AND_COLOR_AND_FABRIC_IN_DESCENDING
}
